### PR TITLE
Add arg support for the around command (allows to create custom shortcuts in keybindings.json)

### PR DESCRIPTION
**Pull request by pomdtr**
It allows to create custom shortcuts in `keybindings.json`

See https://code.visualstudio.com/docs/getstarted/keybindings#_command-arguments

### CODE REVIEW

**Comment by pomdtr** [comment]
Looks like i was using my old fork, i'll update the code.

**Comment by abingham** [comment]
Thanks for putting this together!

This change look OK. In the future I'd prefer you not include unnecessary formatting changes in PRs; it just makes it harder for me to see what the real change is.

The only change I want is for you to include something in the README about this so that people know it's available.

**Comment by pomdtr** [comment]
Done :)

**Comment by abingham** [comment]
This looks great now, thanks! I'll merge it in right away and hopefully have a new version published soon.

**Comment by pomdtr** [comment]
Thanks a lot for your responsiveness :)

**Pull request merged**
