### PR TITLE
add multiple char surrounding

### PR DESCRIPTION
**Pull request by pomdtr**
For example, in jinja template, you often want to surround a var by two brackets and a space:
By putting `{{ ` in the prompt, you will change `var` to `{{ var }}`.

### CODE REVIEW

**Comment by abingham** [comment]
My main problem with this PR is that it breaks one of my favorite features. Currently I get different behavior if I use "[" or "]" as the trigger; one puts spaces in, another doesn't.

Can't you get the feature you want just by adding `"{{ ": ["{{ ", " }}"]` to the `around.pairs` mapping in your settings?

**Comment by pomdtr** [comment]
Thanks for the quick response !

I prefer a dynamic behavior than manually changing the settings. I understand the issue, so i did restore the previous configuration. These change should now be back-compatible.

**Comment by pomdtr** [comment]
However it does not work as i want for the jinja templates :(.

Btw, you can obtain the same result by typing `{ `.

**Comment by abingham** [comment]
I wonder if we could have the best of both worlds. This isn't entirely thought-through, but maybe something like this. We could have two mappings: an "exact match" mapping and a "dynamic" mapping. If the trigger exactly matches an entire key in the "exact" mapping, we use the value for closing and we're done. Otherwise, we do a character-by-character lookup in the "dynamic" map as you've implemented. (And we'd keep the fallback we currently have where, if no mapping is found at all, we simply use the same character for open and close.)

I think this would support all of the use-cases I have considered (e.g. wacky things like HTML comment tags), and it lets us use the concise algorithm you've written. Does that approach actually make sense?

**Comment by pomdtr** [comment]
Yes i think it should work. Another solution is to exchange the behavior of opening and closing element, since we are unlikely to using the closing char in the dynamic mapping, as i implemented in my last commit.

**Comment by abingham** [comment]
> Another solution is to exchange the behavior of opening and closing element,

I'm not sure I understand. You mean using the closing element as a key in the "exact" map or something?

**Comment by pomdtr** [comment]
I did just exchange the mapping between the closing element and the opening element. See the package.json changes for reference.

I'm not sure it is worth to implements two mappings in the settings.json file. To be fair, i can obtain my wanted behavior by changing my settings.

**Comment by pomdtr** [comment]
So if you prefer to keep the existing behavior as it is, we can also restore the package.json file, and i'll customize my own settings.json :)

**Comment by abingham** [comment]
The more I think about it, the more I like the dynamic idea you've implemented, though I do want to keep existing behavior for cases where it's needed. Perhaps we don't actually need two mappings; we can use a single mapping, but we query it as I described earlier: first for an exact match, and if that fails then go character by character. Ultimately, I think it would be very cool if things like jinja tags "just worked"...that feels like a natural behavior of the system.

**Comment by pomdtr** [comment]
I have trouble to see how we can achive this behaviour without two mappings, or having constraining the key for exact match to be constitued of multiple characters.

**Comment by pomdtr** [comment]
I did add support for newlines, allowing to create some complex surrounding. For creating a markdown code block, you can select multiples lines and use: 

```
```\n
```

**Comment by abingham** [comment]
This is all really good! I'm going to merge this is in, and I may mess around with it a but more. Thanks!

**Comment by abingham** [comment]
BTW, I finally managed to get this version published on the marketplace. Sorry for the delay. I find Microsoft's login/auth/account system completely baffling.

**Pull request merged**
